// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// prs
arma::mat prs(std::string input, bool debug, arma::uword n, arma::mat weights);
RcppExport SEXP aprs_prs(SEXP inputSEXP, SEXP debugSEXP, SEXP nSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input(inputSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(prs(input, debug, n, weights));
    return rcpp_result_gen;
END_RCPP
}
// split
void split(const std::string& s, char delim, std::vector<std::string>& elems);
RcppExport SEXP aprs_split(SEXP sSEXP, SEXP delimSEXP, SEXP elemsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type s(sSEXP);
    Rcpp::traits::input_parameter< char >::type delim(delimSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string>& >::type elems(elemsSEXP);
    split(s, delim, elems);
    return R_NilValue;
END_RCPP
}
