# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Construct several polygenic risk scores from a matrix of weights. 
#' @param name Path to .ped file (or binary file, working on this now). 
#' @param weights A matrix of weights with each row being beta corresponding to the association between SNP at that position and the outcome. 
#' @export
prs_test <- function(input, debug, n, weights) {
    .Call('aprs_prs_test', PACKAGE = 'aprs', input, debug, n, weights)
}

rcpparma_hello_world <- function() {
    .Call('aprs_rcpparma_hello_world', PACKAGE = 'aprs')
}

rcpparma_outerproduct <- function(x) {
    .Call('aprs_rcpparma_outerproduct', PACKAGE = 'aprs', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('aprs_rcpparma_innerproduct', PACKAGE = 'aprs', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('aprs_rcpparma_bothproducts', PACKAGE = 'aprs', x)
}

split <- function(s, delim, elems) {
    invisible(.Call('aprs_split', PACKAGE = 'aprs', s, delim, elems))
}

