# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Construct a raw weighted PRS from cleaned input
#' @param map plink style .map file path. (char)
#' @param ped plink style .ped file path. (char)
#' @param assoc A vector of beta coefficients passed from R. (arma::vec)
wprs <- function(map, ped, assoc) {
    .Call('aprs_wprs', PACKAGE = 'aprs', map, ped, assoc)
}

